version: '3.9'
services:
  planilha:
    build:
      context: .
      dockerfile: Dockerfile.planilha
    volumes:
      - .:/app

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    volumes:
      - .:/app

  apostas:
    build:
      context: .
      dockerfile: Dockerfile.apostas
    volumes:
      - .:/app

  flashscore:
    build:
      context: .
      dockerfile: Dockerfile.flashscore
    volumes:
      - .:/app

  gerenciamento:
    build:
      context: .
      dockerfile: Dockerfile.gerenciamento
    volumes:
      - .:/app