version: '3'
services:
  main_interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  image_processing:
    build:
      context: .
      dockerfile: Dockerfile.image
    volumes:
      - .:/app

  spreadsheet_service:
    build:
      context: .
      dockerfile: Dockerfile.spreadsheet
    volumes:
      - .:/app

  flashscore_service:
    build:
      context: .
      dockerfile: Dockerfile.flashscore
    volumes:
      - .:/app

  betting_site_service:
    build:
      context: .
      dockerfile: Dockerfile.betting
    volumes:
      - .:/app

volumes:
  app_data: