version: '3.9'
services:
  planilha:
    build:
      context: .
      dockerfile: Dockerfile.planilha
    volumes:
      - .:/app
      - ./backups:/app/backups

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    volumes:
      - .:/app
      - ./backups:/app/backups

  apostas:
    build:
      context: .
      dockerfile: Dockerfile.apostas
    volumes:
      - .:/app
      - ./backups:/app/backups

  flashscore:
    build:
      context: .
      dockerfile: Dockerfile.flashscore
    volumes:
      - .:/app
      - ./backups:/app/backups

  gerenciamento:
    build:
      context: .
      dockerfile: Dockerfile.gerenciamento
    volumes:
      - .:/app
      - ./backups:/app/backups